version: '3'

# TODO: make network more secure
services:
  postgres:
    env_file: .env
    build: ./docker/postgres/
    ports:
      - $POSTGRES_PORT:5432
    healthcheck:
      test: ["CMD", "pg_isready -U backend"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  mongo:
    image: mongo:4
    env_file: .env
    command: --quiet
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGO_DB
    ports:
      - $MONGO_PORT:27017
    healthcheck:
      test: ["CMD","mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
  
  redis:
    image: "redis:7.0.0-alpine"
    env_file: .env
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  mongo_data:
  redis_data:

networks: 
  default: 
    name: app_network