// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: dictionary.proto

package dictionary

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Definition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text    string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Example string `protobuf:"bytes,2,opt,name=example,proto3" json:"example,omitempty"`
}

func (x *Definition) Reset() {
	*x = Definition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dictionary_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Definition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Definition) ProtoMessage() {}

func (x *Definition) ProtoReflect() protoreflect.Message {
	mi := &file_dictionary_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Definition.ProtoReflect.Descriptor instead.
func (*Definition) Descriptor() ([]byte, []int) {
	return file_dictionary_proto_rawDescGZIP(), []int{0}
}

func (x *Definition) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Definition) GetExample() string {
	if x != nil {
		return x.Example
	}
	return ""
}

type Meaning struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PartOfSpeech string        `protobuf:"bytes,1,opt,name=part_of_speech,json=partOfSpeech,proto3" json:"part_of_speech,omitempty"`
	Definitions  []*Definition `protobuf:"bytes,2,rep,name=definitions,proto3" json:"definitions,omitempty"`
	Synonyms     []string      `protobuf:"bytes,3,rep,name=synonyms,proto3" json:"synonyms,omitempty"`
	Antonyms     []string      `protobuf:"bytes,4,rep,name=antonyms,proto3" json:"antonyms,omitempty"`
}

func (x *Meaning) Reset() {
	*x = Meaning{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dictionary_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Meaning) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meaning) ProtoMessage() {}

func (x *Meaning) ProtoReflect() protoreflect.Message {
	mi := &file_dictionary_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meaning.ProtoReflect.Descriptor instead.
func (*Meaning) Descriptor() ([]byte, []int) {
	return file_dictionary_proto_rawDescGZIP(), []int{1}
}

func (x *Meaning) GetPartOfSpeech() string {
	if x != nil {
		return x.PartOfSpeech
	}
	return ""
}

func (x *Meaning) GetDefinitions() []*Definition {
	if x != nil {
		return x.Definitions
	}
	return nil
}

func (x *Meaning) GetSynonyms() []string {
	if x != nil {
		return x.Synonyms
	}
	return nil
}

func (x *Meaning) GetAntonyms() []string {
	if x != nil {
		return x.Antonyms
	}
	return nil
}

type WordEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Word     string     `protobuf:"bytes,2,opt,name=word,proto3" json:"word,omitempty"`
	Phonetic string     `protobuf:"bytes,3,opt,name=phonetic,proto3" json:"phonetic,omitempty"`
	Meanings []*Meaning `protobuf:"bytes,4,rep,name=meanings,proto3" json:"meanings,omitempty"`
}

func (x *WordEntry) Reset() {
	*x = WordEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dictionary_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WordEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordEntry) ProtoMessage() {}

func (x *WordEntry) ProtoReflect() protoreflect.Message {
	mi := &file_dictionary_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordEntry.ProtoReflect.Descriptor instead.
func (*WordEntry) Descriptor() ([]byte, []int) {
	return file_dictionary_proto_rawDescGZIP(), []int{2}
}

func (x *WordEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WordEntry) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *WordEntry) GetPhonetic() string {
	if x != nil {
		return x.Phonetic
	}
	return ""
}

func (x *WordEntry) GetMeanings() []*Meaning {
	if x != nil {
		return x.Meanings
	}
	return nil
}

type Word struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Word string `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
}

func (x *Word) Reset() {
	*x = Word{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dictionary_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Word) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Word) ProtoMessage() {}

func (x *Word) ProtoReflect() protoreflect.Message {
	mi := &file_dictionary_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Word.ProtoReflect.Descriptor instead.
func (*Word) Descriptor() ([]byte, []int) {
	return file_dictionary_proto_rawDescGZIP(), []int{3}
}

func (x *Word) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

type WordId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WordId string `protobuf:"bytes,1,opt,name=wordId,proto3" json:"wordId,omitempty"`
}

func (x *WordId) Reset() {
	*x = WordId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dictionary_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WordId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordId) ProtoMessage() {}

func (x *WordId) ProtoReflect() protoreflect.Message {
	mi := &file_dictionary_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordId.ProtoReflect.Descriptor instead.
func (*WordId) Descriptor() ([]byte, []int) {
	return file_dictionary_proto_rawDescGZIP(), []int{4}
}

func (x *WordId) GetWordId() string {
	if x != nil {
		return x.WordId
	}
	return ""
}

var File_dictionary_proto protoreflect.FileDescriptor

var file_dictionary_proto_rawDesc = []byte{
	0x0a, 0x10, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x22, 0x3a,
	0x0a, 0x0a, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x22, 0xa1, 0x01, 0x0a, 0x07, 0x4d,
	0x65, 0x61, 0x6e, 0x69, 0x6e, 0x67, 0x12, 0x24, 0x0a, 0x0e, 0x70, 0x61, 0x72, 0x74, 0x5f, 0x6f,
	0x66, 0x5f, 0x73, 0x70, 0x65, 0x65, 0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x70, 0x61, 0x72, 0x74, 0x4f, 0x66, 0x53, 0x70, 0x65, 0x65, 0x63, 0x68, 0x12, 0x38, 0x0a, 0x0b,
	0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x2e, 0x44,
	0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x64, 0x65, 0x66, 0x69, 0x6e,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x79, 0x6e, 0x6f, 0x6e, 0x79,
	0x6d, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x73, 0x79, 0x6e, 0x6f, 0x6e, 0x79,
	0x6d, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x6e, 0x74, 0x6f, 0x6e, 0x79, 0x6d, 0x73, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x61, 0x6e, 0x74, 0x6f, 0x6e, 0x79, 0x6d, 0x73, 0x22, 0x7c,
	0x0a, 0x09, 0x57, 0x6f, 0x72, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x77,
	0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x74, 0x69, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x74, 0x69, 0x63, 0x12, 0x2f, 0x0a, 0x08, 0x6d,
	0x65, 0x61, 0x6e, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x2e, 0x4d, 0x65, 0x61, 0x6e, 0x69,
	0x6e, 0x67, 0x52, 0x08, 0x6d, 0x65, 0x61, 0x6e, 0x69, 0x6e, 0x67, 0x73, 0x22, 0x1a, 0x0a, 0x04,
	0x57, 0x6f, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x20, 0x0a, 0x06, 0x57, 0x6f, 0x72, 0x64,
	0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x6f, 0x72, 0x64, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x77, 0x6f, 0x72, 0x64, 0x49, 0x64, 0x32, 0xb5, 0x01, 0x0a, 0x11, 0x44,
	0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x30, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x10, 0x2e, 0x64, 0x69, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x2e, 0x57, 0x6f, 0x72, 0x64, 0x1a, 0x12, 0x2e, 0x64,
	0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x2e, 0x57, 0x6f, 0x72, 0x64, 0x49, 0x64,
	0x22, 0x00, 0x12, 0x36, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x12, 0x12, 0x2e,
	0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x2e, 0x57, 0x6f, 0x72, 0x64, 0x49,
	0x64, 0x1a, 0x15, 0x2e, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x2e, 0x57,
	0x6f, 0x72, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x22, 0x00, 0x12, 0x36, 0x0a, 0x09, 0x47, 0x65,
	0x74, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x2e, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x61, 0x72, 0x79, 0x2e, 0x57, 0x6f, 0x72, 0x64, 0x1a, 0x15, 0x2e, 0x64, 0x69, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x2e, 0x57, 0x6f, 0x72, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x22, 0x00, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x72, 0x6b, 0x66, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x2f, 0x65, 0x6e, 0x67, 0x6c, 0x69,
	0x73, 0x68, 0x5f, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64,
	0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_dictionary_proto_rawDescOnce sync.Once
	file_dictionary_proto_rawDescData = file_dictionary_proto_rawDesc
)

func file_dictionary_proto_rawDescGZIP() []byte {
	file_dictionary_proto_rawDescOnce.Do(func() {
		file_dictionary_proto_rawDescData = protoimpl.X.CompressGZIP(file_dictionary_proto_rawDescData)
	})
	return file_dictionary_proto_rawDescData
}

var file_dictionary_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_dictionary_proto_goTypes = []interface{}{
	(*Definition)(nil), // 0: dictionary.Definition
	(*Meaning)(nil),    // 1: dictionary.Meaning
	(*WordEntry)(nil),  // 2: dictionary.WordEntry
	(*Word)(nil),       // 3: dictionary.Word
	(*WordId)(nil),     // 4: dictionary.WordId
}
var file_dictionary_proto_depIdxs = []int32{
	0, // 0: dictionary.Meaning.definitions:type_name -> dictionary.Definition
	1, // 1: dictionary.WordEntry.meanings:type_name -> dictionary.Meaning
	3, // 2: dictionary.DictionaryService.Create:input_type -> dictionary.Word
	4, // 3: dictionary.DictionaryService.GetById:input_type -> dictionary.WordId
	3, // 4: dictionary.DictionaryService.GetByName:input_type -> dictionary.Word
	4, // 5: dictionary.DictionaryService.Create:output_type -> dictionary.WordId
	2, // 6: dictionary.DictionaryService.GetById:output_type -> dictionary.WordEntry
	2, // 7: dictionary.DictionaryService.GetByName:output_type -> dictionary.WordEntry
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_dictionary_proto_init() }
func file_dictionary_proto_init() {
	if File_dictionary_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dictionary_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Definition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dictionary_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Meaning); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dictionary_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WordEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dictionary_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Word); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dictionary_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WordId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dictionary_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dictionary_proto_goTypes,
		DependencyIndexes: file_dictionary_proto_depIdxs,
		MessageInfos:      file_dictionary_proto_msgTypes,
	}.Build()
	File_dictionary_proto = out.File
	file_dictionary_proto_rawDesc = nil
	file_dictionary_proto_goTypes = nil
	file_dictionary_proto_depIdxs = nil
}
